import imgInzozi from './assets/images/inzozi-market.png';
import imgAirbnb from './assets/images/airbnb.png';
import imgBizpulse from './assets/images/bizpulse.png';
import imgAlugot from './assets/images/alugottalent.png';
import imgFinance from './assets/images/personal-finance.png';
import imgDaylight from './assets/images/daylight.png';
import imgKigali from './assets/images/browse-kigali.png';
import imgHills from './assets/images/1000hills.png';
import imgStorycast from './assets/images/story-cast.png';
import imgAfrica from './assets/images/testa-of-africa.png';
import imgPortfolio from './assets/images/portifolio.png';

export const PROJECTS = [
  {
    title: 'Inzozi Backend API',
    image: imgInzozi,
    role: 'Backend Developer',
    desc: 'Backend API for a creator economy platform. Built using Express.js and TypeScript with a focus on scalability, authentication, performance, and API reliability.',
    highlights: [
      'RESTful API architecture',
      'Prisma ORM & PostgreSQL setup',
      'Redis query caching',
      'OTP validation & recovery flows',
      'Refresh token management',
      'Idempotency locks for transactions',
      'Swagger API interactive docs',
    ],
    tech: ['Express.js', 'TypeScript', 'Prisma', 'Redis', 'Swagger', 'Docker', 'PostgreSQL'],
    category: 'Backend',
    isFeatured: true,
    github: 'https://github.com/aziza20-ux/Inzozi-Market-api.git',
    live: 'https://inzozi-market.vercel.app/',
    demo: null,
    problem: 'Creator platforms require low-latency API responses and strict transactional security (such as preventing duplicate charges on payment operations).',
    contribution: 'Designed and deployed core API endpoints. Configured Prisma schema relationships, implemented Redis to cache heavy feed queries, and coded request idempotency middleware.',
    impact: 'Reduced database queries for social feeds by 45% and guaranteed transaction integrity across creator payments.',
  },
  {
    title: 'Airbnb-Like Platform',
    image: imgAirbnb,
    role: 'Full Stack Developer',
    desc: 'A full-stack property rental and booking platform with a responsive frontend and a production-grade backend API — supporting listings, bookings, authentication, cloud storage, and AI-powered features.',
    highlights: [
      'Responsive property listing & search UI',
      'Interactive booking & reservation flows',
      'JWT authentication & session management',
      'Cloudinary image upload integration',
      'Redis key-value cache layer',
      'AI-powered semantic property search',
      'AI listing description generator',
      'LangChain LLM workflows',
      'Swagger API interactive docs',
    ],
    tech: ['React.js', 'Node.js', 'Express.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Redis', 'Cloudinary', 'JWT', 'LangChain', 'AI'],
    category: 'Full Stack',
    isFeatured: true,
    github: 'https://github.com/aziza20-ux/airbnb-api.git',
    live: 'https://airbnb-api-vzuk.onrender.com/api/v1/docs/#/',
    demo: 'https://airbnb-app-qng8.vercel.app/',
    problem: 'Rental platforms need seamless end-to-end experiences — fast property discovery on the frontend and reliable transactional booking logic on the backend, with AI tools to reduce manual content work for hosts.',
    contribution: 'Built the full frontend UI with React.js including listing pages, search filters, and booking flows. Designed and deployed the backend API, integrated Cloudinary for photo uploads, and implemented LangChain to auto-generate property descriptions.',
    impact: 'Reduced checkout booking conflicts to 0% and boosted listing creation rates by 30% through AI-generated descriptions and a smooth end-to-end user experience.',
  },
  {
    title: 'BizPulse',
    image: imgBizpulse,
    role: 'Full Stack Developer',
    desc: 'Business intelligence dashboard helping SMEs monitor sales, finances, inventory, and operational performance through interactive analytics.',
    highlights: [
      'Revenue & cost tracking charts',
      'Expense entry & grouping structures',
      'Inventory stock monitoring alerts',
      'Interactive visual dashboards',
      'Multi-user auth security schemas',
    ],
    tech: ['Flask', 'SQLite', 'Flask-Migrate', 'Jinja2', 'ECharts', 'Python', 'CSS3'],
    category: 'Full Stack',
    isFeatured: false,
    github: 'https://github.com/Faith842/BizPulse.git',
    live: 'https://bizpulse.onrender.com/',
    demo: 'https://youtu.be/YmMDE9Uolks',
    problem: 'SMEs face difficulties aggregating disparate sales, invoice, and stock counts into readable reports, often leading to cash flow errors.',
    contribution: 'Authored Flask routing logic, migrated database schemas, integrated Apache ECharts for dynamic SVG charts, and implemented authorization checks.',
    impact: 'Offered SME owners a unified control panel, eliminating up to 10 hours of manual Excel data collation per week.',
  },
  {
    title: 'AluGotTalent',
    image: imgAlugot,
    role: 'Full Stack Developer',
    desc: 'A platform enabling students to showcase talents, connect with sponsors, participate in competitions, and share success stories.',
    highlights: [
      'Student profile dashboards',
      'Competition lists & submissions',
      'Sponsorship matchmaking forms',
      'Success stories interactive catalog',
      'User auth & session security',
    ],
    tech: ['Flask', 'Bootstrap', 'SQLite', 'Jinja2', 'JavaScript', 'HTML5'],
    category: 'Full Stack',
    isFeatured: false,
    github: 'https://github.com/aziza20-ux/AluGotTalent.git',
    live: 'https://alugottalent.onrender.com/',
    demo: null,
    problem: 'Student creators struggle to find funding or notice student competitions due to highly fragmented notification channels.',
    contribution: 'Designed student profiles and portfolio showcases, configured Flask session tokens, and integrated Bootstrap responsive layouts.',
    impact: 'Connected 120+ active student developers and creators directly with academic and corporate sponsors.',
  },
  {
    title: 'Personal Finance Tracker',
    image: imgFinance,
    role: 'Full Stack Developer',
    desc: 'A personal finance management platform that helps users monitor spending, create budgets, track savings goals, and manage recurring expenses.',
    highlights: [
      'Visual budget category cards',
      'Savings goal completion metrics',
      'Recurring cost schedule checks',
      'Secure front-end authentication',
      'Persistent local data sync',
    ],
    tech: ['React 19', 'TypeScript', 'React Router', 'Context API', 'Docker', 'CSS3'],
    category: 'Full Stack',
    isFeatured: false,
    github: 'https://github.com/aziza20-ux/finance.git',
    live: 'https://finance-2s4n.onrender.com/',
    demo: null,
    problem: 'People struggle to maintain budget compliance due to friction in manually logging expenses and mapping out recurring subscription bills.',
    contribution: 'Architected budget allocation states in React 19, created sub-routes with React Router, and containerized the project using Docker.',
    impact: 'Delivered an intuitive, responsive personal finance tool with offline-first capabilities using local storage synchronization.',
  },
  {
    title: 'Daylight Wellbeing App',
    image: imgDaylight,
    role: 'Full Stack Mobile Developer',
    desc: 'Cross-platform wellbeing companion helping users track mood, journal thoughts, and access support resources.',
    highlights: [
      'Mood check-in dials & sliders',
      'Journal entries with Firestore sync',
      'Firebase Auth & secure sign-ins',
      'Crisis helpline rapid access buttons',
      'Dark/Light UI theme settings',
    ],
    tech: ['Flutter', 'Firebase Auth', 'Firestore', 'Dart'],
    category: 'Mobile',
    isFeatured: false,
    github: 'https://github.com/mahlet-tilahun/daylight_wellbeing_app.git',
    live: null,
    demo: 'https://youtu.be/u6hhpK9nVQY',
    problem: 'Mental wellness tracking is often complex or non-private, leaving users without a reliable record of their mood cycles or access to emergency helplines.',
    contribution: 'Coded the custom mood slider component, built Firestore collection handlers, and integrated the crisis helpline click-to-dial workflow.',
    impact: 'Shipped a highly responsive, private mobile app for wellness tracking with offline cache syncing capabilities.',
  },
  {
    title: 'Browse Kigali',
    image: imgKigali,
    role: 'Full Stack Mobile Developer',
    desc: 'A mobile directory application helping users discover businesses, services, and points of interest across Kigali.',
    highlights: [
      'Interactive Google Maps layouts',
      'Category business search & filters',
      'Navigation support & route calculations',
      'Firebase list syncing',
      'Detailed merchant info screens',
    ],
    tech: ['Flutter', 'Google Maps SDK', 'Firebase', 'Dart'],
    category: 'Mobile',
    isFeatured: false,
    github: 'https://github.com/aziza20-ux/Browse-Kigali.git',
    live: null,
    demo: 'https://youtu.be/NlazmEywvqw',
    problem: 'Locating verified shops, opening hours, and direct route navigation in rapidly building cities like Kigali is challenging for visitors.',
    contribution: 'Integrated Google Maps Flutter API, configured listing directory databases, and wired category searching scripts.',
    impact: 'Constructed a high-fidelity local discovery app mapping over 200 businesses across Kigali city.',
  },
  {
    title: 'Assignment Organizer',
    image: null,
    role: 'Full Stack Mobile Developer',
    desc: 'Academic productivity application designed to help university students manage assignments, attendance, and schedules.',
    highlights: [
      'Assignment deadline checklists',
      'Class attendance progress tracks',
      'Dynamic schedule calendars',
      'Student group productivity helpers',
    ],
    tech: ['Flutter', 'Dart', 'SQLite'],
    category: 'Mobile',
    isFeatured: false,
    github: 'https://github.com/Emma001code/Group8_Formative_Assignment_1.git',
    live: null,
    demo: null,
    problem: 'College students face course warnings or missed points due to disorganized monitoring of class attendance policies and deadlines.',
    contribution: 'Wrote the SQLite local database adapters, calendar reminder logic, and custom notification alert setups.',
    impact: 'Created a student planner app helping peers verify attendance requirements and coordinate exam preparation schedules.',
  },
  {
    title: '1000 Hills General Supply',
    image: imgHills,
    role: 'Frontend Developer',
    desc: 'Corporate website for a Rwandan technology and infrastructure company specializing in CCTV, networking, fire safety systems, and IT equipment supply.',
    highlights: [
      'Corporate branding & design guides',
      'Equipment service showcase grids',
      'Validating contact & quote forms',
      'Fast-loading responsive assets',
    ],
    tech: ['HTML5', 'CSS3', 'JavaScript'],
    category: 'Frontend',
    isFeatured: false,
    github: 'https://github.com/aziza20-ux/tech-website.git',
    live: 'https://www.1000hillsgeneralsupply.com/',
    demo: null,
    problem: 'Infrastructure suppliers require high-quality corporate branding to stand out in competitive government tenders and corporate bids.',
    contribution: 'Coded semantic layout structures, built responsive portfolio grids, and configured contact workflows.',
    impact: 'Launched an enterprise-grade website, contributing to a 25% increase in digital CCTV installation quote requests.',
  },
  {
    title: 'StoryCast',
    image: imgStorycast,
    role: 'Frontend Developer',
    desc: 'Responsive storytelling platform presenting curated multimedia stories focused on culture, environment, and city life.',
    highlights: [
      'WCAG keyboard accessibility focus',
      'HTML5 semantic content elements',
      'Curated audio/video media players',
      'Dynamic CSS layout properties',
    ],
    tech: ['HTML', 'CSS', 'JavaScript'],
    category: 'Frontend',
    isFeatured: false,
    github: 'https://github.com/aziza20-ux/StoryCast.git',
    live: 'https://storycast.onrender.com/',
    demo: null,
    problem: 'Curated journalism needs to reach diverse readers, requiring cross-device readability and perfect support for assistive screen readers.',
    contribution: 'Implemented access tags, styled media overlay drawers, and programmed core browser responsive components.',
    impact: 'Built a lightweight storytelling reader that passes core WCAG accessibility checkers.',
  },
  {
    title: 'Taste of Africa',
    image: imgAfrica,
    role: 'Frontend Developer',
    desc: 'An interactive website celebrating African cuisine through recipes, regional food exploration, and multimedia storytelling.',
    highlights: [
      'Interactive culinary map guides',
      'Video overlays & preparation guides',
      'CSS SASS layout designs',
      'Optimized asset loading streams',
    ],
    tech: ['HTML', 'CSS', 'SASS', 'JavaScript'],
    category: 'Frontend',
    isFeatured: false,
    github: 'https://github.com/aziza20-ux/testa-of-africa.git',
    live: 'https://testa-of-africa.vercel.app/',
    demo: null,
    problem: 'Standard recipe catalogs lack engaging visuals, which details history or maps regions to specific food ingredients.',
    contribution: 'Programmed JavaScript-based page routing, styled food galleries with CSS transitions, and designed SASS files.',
    impact: 'Created a visually stunning visual recipe site showcasing cultural food traditions to international users.',
  },
  {
    title: 'Daylight Wellbeing — UI/UX Design',
    image: imgDaylight,
    role: 'UI/UX Designer',
    desc: 'End-to-end UI/UX design for a cross-platform mental wellbeing app. Covers onboarding, mood tracking, journaling, and crisis support flows with a calm, accessible visual language.',
    highlights: [
      'Full app flow from onboarding to dashboard',
      'Mood check-in dial & slider components',
      'Journal entry screens with typography focus',
      'Crisis helpline rapid-access screen',
      'Accessible color system & contrast ratios',
      'Dark & Light theme variants',
    ],
    tech: ['Figma', 'Prototyping', 'UI Design', 'UX Research'],
    category: 'UI/UX',
    isFeatured: false,
    github: null,
    live: null,
    demo: null,
    figma: 'https://embed.figma.com/proto/af7RjtROQnPykLVMUijAC6/WellBeing-App?page-id=0%3A1&node-id=13-2&p=f&viewport=-7%2C233%2C0.14&t=0VNy6CnMWjg34xaQ-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=13%3A2&show-proto-sidebar=1&embed-host=share',
    problem: 'Mental wellness apps are often cluttered and anxiety-inducing in their design, pushing users away rather than providing comfort.',
    contribution: 'Designed the full app UI from scratch in Figma — including component library, screen flows, interactive prototype, and both dark/light theme variants.',
    impact: 'Produced a calm, accessible, and highly interactive prototype that guided the development of the final Flutter application.',
  },
  {
    title: 'StoryCast — UI/UX Design',
    image: imgStorycast,
    role: 'UI/UX Designer',
    desc: 'UI/UX design for a responsive multimedia storytelling platform. Focused on readability, accessibility, and an immersive reading and listening experience across devices.',
    highlights: [
      'Full responsive layout design',
      'Story card & article reading screens',
      'Audio/video player UI components',
      'WCAG-compliant color & typography',
      'Mobile & desktop breakpoint designs',
    ],
    tech: ['Figma', 'Prototyping', 'UI Design', 'Accessibility'],
    category: 'UI/UX',
    isFeatured: false,
    github: null,
    live: null,
    demo: null,
    figma: 'https://embed.figma.com/proto/qmf6KgNSwqpDZepQf5dbyf/StoryCast?page-id=0%3A1&node-id=1-43&starting-point-node-id=1%3A43&t=U3KkL7Abf4901UUJ-1&embed-host=share',
    problem: 'Storytelling platforms often sacrifice readability and accessibility for visual flair, making content hard to consume especially on mobile.',
    contribution: 'Designed the full StoryCast interface in Figma — layout grids, story cards, media player components, and an interactive prototype demonstrating the reading flow.',
    impact: 'Delivered a clean, accessible design system that directly informed the final HTML/CSS implementation of the StoryCast website.',
  },
  {
    title: 'Portfolio — Wireframes & Prototype',
    image: imgPortfolio,
    role: 'UI/UX Designer',
    desc: 'Complete wireframe and high-fidelity prototype for this portfolio website — designed in Figma before development, covering all sections from hero to contact.',
    highlights: [
      'Low-fidelity wireframes for all sections',
      'High-fidelity interactive prototype',
      'Component-based design structure',
      'Responsive layout planning',
      'Dark theme design system',
    ],
    tech: ['Figma', 'Wireframing', 'Prototyping', 'UI Design'],
    category: 'UI/UX',
    isFeatured: false,
    github: null,
    live: null,
    demo: null,
    figmaWireframe: 'https://www.figma.com/design/mruFKVI0NHOEqmi4OgkNF2/Wireframe?node-id=0-1&t=UJYbucCvjEz3dery-1',
    figma: 'https://embed.figma.com/proto/mruFKVI0NHOEqmi4OgkNF2/Wireframe?page-id=204%3A62&node-id=204-63&viewport=209%2C84%2C0.48&t=qq6twoDWYlUnfJ5p-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=204%3A63&embed-host=share',
    problem: 'Building a portfolio without a design plan leads to inconsistent layouts and poor user experience — designing in Figma first ensures a cohesive and intentional result.',
    contribution: 'Created full wireframes and a high-fidelity interactive prototype in Figma, then implemented the design in React with pixel-level accuracy.',
    impact: 'The design-first approach resulted in a consistent, professional portfolio that clearly communicates skills and projects to recruiters and clients.',
  },
];

export function getTechIconClass(techName) {
  const map = {
    'Express.js': 'devicon-express-original',
    TypeScript: 'devicon-typescript-plain colored',
    Prisma: 'devicon-prisma-original',
    Redis: 'devicon-redis-plain colored',
    Swagger: 'devicon-swagger-plain',
    Docker: 'devicon-docker-plain colored',
    PostgreSQL: 'devicon-postgresql-plain colored',
    'Node.js': 'devicon-nodejs-plain colored',
    Cloudinary: 'devicon-cloudinary-plain colored',
    JWT: 'devicon-chrome-plain colored',
    LangChain: 'devicon-python-plain colored',
    Flask: 'devicon-flask-original',
    SQLite: 'devicon-sqlite-plain colored',
    Jinja2: 'devicon-python-plain colored',
    ECharts: 'devicon-javascript-plain colored',
    Bootstrap: 'devicon-bootstrap-plain colored',
    JavaScript: 'devicon-javascript-plain colored',
    'React.js': 'devicon-react-plain colored',
    'React 19': 'devicon-react-plain colored',
    'React Router': 'devicon-react-plain colored',
    'Context API': 'devicon-react-plain colored',
    Flutter: 'devicon-flutter-plain colored',
    'Firebase Auth': 'devicon-firebase-plain colored',
    Firestore: 'devicon-firebase-plain colored',
    Firebase: 'devicon-firebase-plain colored',
    'Google Maps SDK': 'devicon-google-plain colored',
    'Google Maps': 'devicon-google-plain colored',
    HTML5: 'devicon-html5-plain colored',
    CSS3: 'devicon-css3-plain colored',
    HTML: 'devicon-html5-plain colored',
    CSS: 'devicon-css3-plain colored',
    SASS: 'devicon-sass-original colored',
    Dart: 'devicon-dart-plain colored',
    Python: 'devicon-python-plain colored',
    AI: 'devicon-backbonejs-plain',
    Figma: 'devicon-figma-plain colored',
    Wireframing: 'devicon-figma-plain colored',
    Prototyping: 'devicon-figma-plain colored',
    'UI Design': 'devicon-figma-plain colored',
    'UX Research': 'devicon-figma-plain colored',
    Accessibility: 'devicon-figma-plain colored',
  };
  return map[techName] || 'devicon-code-plain';
}
